import { test } from "node:test";
import assert from "node:assert/strict";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Parser, Language } from "web-tree-sitter";
import { verifyGrammarManifest } from "../../grammars/verify.js";

const wasmDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "grammars", "wasm");

test("every built grammar WASM file matches its recorded sha256 (packaged grammar integrity check)", () => {
  const result = verifyGrammarManifest();
  assert.deepEqual(result.errors, []);
  assert.equal(result.ok, true);
  assert.equal(result.manifest.grammars.length, 8);
});

test("all four V0.1 language families plus their embedded CFML grammars are present", () => {
  const result = verifyGrammarManifest();
  const languages = result.manifest.grammars.map((g) => g.language).sort();
  assert.deepEqual(languages, ["cfml", "cfquery", "cfscript", "css", "javascript", "python", "tsx", "typescript"]);
});

/**
 * docs/TESTING_GOLDEN_EVAL.md "Grammar load" layer requires every packaged
 * grammar to load, report identity, match hash (covered above), AND parse a
 * minimal fixture. The sha256 check alone doesn't prove a grammar loads —
 * notably, the embedded `cfquery` and `css` grammars are built and advertised
 * in Capabilities (embeddedLanguages), and the adapter tests exercise both.
 * This test independently proves all 8 are real, loadable, parseable WASM
 * modules regardless of which adapter code path loads them.
 */
test("every grammar in the manifest actually loads via web-tree-sitter and parses a minimal fixture", async () => {
  await Parser.init();
  const result = verifyGrammarManifest();

  // typescript/tsx report Language.name === null (ABI 14, vs 15 for the other
  // six grammars) — @cfmleditor/tree-sitter-cfml and tree-sitter-javascript/
  // python ship a parser.c generated by a tree-sitter-cli new enough to embed
  // metadata identity; tree-sitter-typescript@0.23.2's pre-generated parser.c
  // predates that. Parsing is unaffected (see the TypeScript/TSX adapter
  // tests) — this only means those two grammars can't self-report identity
  // via Language.name, so the assertion below tolerates null instead of
  // hiding the discrepancy by skipping the check entirely.
  const knownMissingIdentity = new Set(["typescript", "tsx"]);

  for (const grammar of result.manifest.grammars) {
    const wasmPath = path.join(wasmDir, grammar.wasmFile);
    const language = await Language.load(wasmPath);
    if (knownMissingIdentity.has(grammar.language)) {
      assert.equal(language.name, null, `${grammar.language}: expected the known null Language.name (ABI 14)`);
    } else {
      assert.ok(language.name, `${grammar.language}: Language.load() did not report a language identity`);
    }

    const parser = new Parser();
    let tree: ReturnType<Parser["parse"]> | undefined;
    try {
      parser.setLanguage(language);
      tree = parser.parse("x");
      assert.ok(tree, `${grammar.language}: parse() returned no tree for a minimal fixture`);
      assert.ok(tree.rootNode, `${grammar.language}: parsed tree has no root node`);
    } finally {
      tree?.delete();
      parser.delete();
    }
  }
});
