import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, mkdtempSync, writeFileSync, rmSync, symlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import Ajv from 'ajv';
import { checkUiRegression, validateBundle, capabilities, encodeResult, exitCode, readJson, parseJson, LIMITS } from '../src/index.js';
import { runCli } from '../src/cli.js';
const example = JSON.parse(readFileSync(new URL('../examples/mobile-pass.json',import.meta.url)));
const fixture = () => structuredClone(example);
const run = mutation => {const x = fixture();mutation(x.cases[0],x);return checkUiRegression(x);};
const check = (result,kind) => result.data.checks.find(c => c.kind === kind);
const ajv = new Ajv({strict:true});
const inputSchema = ajv.compile(JSON.parse(readFileSync(new URL('../schema/input.schema.json',import.meta.url))));
const resultSchema = ajv.compile(JSON.parse(readFileSync(new URL('../schema/result.schema.json',import.meta.url))));
test('complete mobile fixture passes all four requested checks',() => {const r=checkUiRegression(fixture());assert.equal(r.status,'pass');assert.equal(r.complete,true);assert.deepEqual(r.data.summary,{pass:4,fail:0,unknown:0});assert.ok(inputSchema(fixture()),JSON.stringify(inputSchema.errors));assert.ok(resultSchema(r),JSON.stringify(resultSchema.errors));});
test('failure fixture identifies four concrete mismatches',() => {const r=checkUiRegression(JSON.parse(readFileSync(new URL('../examples/mobile-fail.json',import.meta.url))));assert.equal(r.status,'fail');assert.equal(r.data.summary.fail,4);});
test('document horizontal overflow fails',()=>assert.equal(check(run(c=>c.document.scrollWidth=391),'overflow').status,'fail'));
test('missing document observation is unknown',()=>assert.equal(check(run(c=>delete c.document),'overflow').status,'unknown'));
test('explicit tolerance covers subpixel overflow',()=>assert.equal(check(run(c=>{c.document.scrollWidth=390.5;c.tolerancePx=1;}),'overflow').status,'pass'));
test('rectangular button intersection fails declared nonoverlap',()=>assert.equal(check(run(c=>c.rectangles[1].x=160),'overlap').status,'fail'));
test('intentional overlap is allowed only by explicit declaration',()=>assert.equal(check(run(c=>{c.rectangles[1].x=160;c.pairs[0].allowOverlap=true;}),'overlap').status,'pass'));
test('touching edges are not a positive rectangle intersection',()=>assert.equal(check(run(c=>c.rectangles[1].x=186),'overlap').status,'pass'));
test('nonintersecting vertical bounds pass declared pair',()=>assert.equal(check(run(c=>{c.rectangles[1].x=16;c.rectangles[1].y=800;}),'overlap').status,'pass'));
test('missing declared element stays unknown',()=>assert.equal(check(run(c=>c.rectangles.pop()),'overlap').status,'unknown'));
test('invisible rectangle stays unknown instead of asserting rendered layout',()=>assert.equal(check(run(c=>c.rectangles[0].visible=false),'overlap').status,'unknown'));
test('no declared pairs stays unknown',()=>assert.equal(check(run(c=>c.pairs=[]),'overlap').status,'unknown'));
test('no rectangle observations stays unknown',()=>assert.equal(check(run(c=>delete c.rectangles),'overlap').status,'unknown'));
test('focus order mismatch fails',()=>assert.equal(check(run(c=>c.focus.observed.reverse()),'focus').status,'fail'));
test('incomplete focus sequence stays unknown',()=>assert.equal(check(run(c=>c.focus.complete=false),'focus').status,'unknown'));
test('missing focus interaction stays unknown',()=>assert.equal(check(run(c=>delete c.focus),'focus').status,'unknown'));
test('empty completed focus observation is a mismatch',()=>assert.equal(check(run(c=>c.focus.observed=[]),'focus').status,'fail'));
test('Back route mismatch fails after settled complete observation',()=>assert.equal(check(run(c=>c.back.observedRouteId='elsewhere'),'back').status,'fail'));
test('Back timeout stays unknown, no retry',()=>assert.equal(check(run(c=>c.back.outcome='timeout'),'back').status,'unknown'));
test('unsettled Back observation stays unknown',()=>assert.equal(check(run(c=>delete c.back.outcome),'back').status,'unknown'));
test('missing Back evidence stays unknown',()=>assert.equal(check(run(c=>delete c.back),'back').status,'unknown'));
test('stale evidence is unknown for every requested check',()=>{const r=run(c=>c.observedAt='2026-09-29T11:59:00Z');assert.equal(r.status,'unknown');assert.equal(r.data.summary.unknown,4);});
test('future evidence is unknown',()=>assert.equal(run(c=>c.observedAt='2026-10-01T11:59:00Z').status,'unknown'));
test('freshness boundary is inclusive',()=>assert.equal(run(c=>c.observedAt='2026-09-30T11:00:00Z').status,'pass'));
test('failure remains visible while incomplete checks keep complete false',()=>{const r=run(c=>{c.document.scrollWidth=500;delete c.back;});assert.equal(r.status,'fail');assert.equal(r.complete,false);assert.equal(exitCode(r),1);});
test('only requested scopes assessed and broader UX never inferred',()=>{const r=run(c=>{c.required=['overflow'];delete c.back;});assert.equal(r.status,'pass');assert.equal(r.data.checks.length,1);assert.match(r.data.scope,/supplied/);});
for(const [name,mutation] of [
 ['empty cases',(c,x)=>x.cases=[]],['duplicate case',(c,x)=>x.cases.push(structuredClone(c))],['unknown screenshot field',c=>c.screenshot='secret screenshot'],['unknown secret field',c=>c.password='dont-echo-secret'],['credential-like identifier',c=>c.id='ghp_secret'],['nonfinite metric',c=>c.viewport.width=Infinity],['negative width',c=>c.rectangles[0].width=-1],['invalid calendar time',c=>c.observedAt='2026-02-30T11:59:00Z'],['duplicate pair ID',c=>c.pairs.push(structuredClone(c.pairs[0]))],['duplicate rectangle ID',c=>c.rectangles.push(structuredClone(c.rectangles[0]))],['self comparison',c=>c.pairs[0].second='save'],['unsupported profile',(c,x)=>x.profile='business-write-v1'],['empty required checks',c=>c.required=[]],['duplicate required checks',c=>c.required=['back','back']],['overlarge tolerance',c=>c.tolerancePx=11],['credential route content',c=>c.back.observedRouteId='https://x/?password=secret']
]) test('reject '+name,()=>{const r=run(mutation);assert.equal(r.status,'error');assert.equal(r.data,null);assert.ok(!JSON.stringify(r).includes('dont-echo-secret'));assert.ok(resultSchema(r));});
test('stable sorting of case and check IDs',()=>{const x=fixture();x.cases[0].id='z';x.cases.push({...structuredClone(x.cases[0]),id:'a'});const checks=checkUiRegression(x).data.checks;assert.deepEqual(checks.map(c=>c.id),checks.map(c=>c.id).sort());});
test('object property order does not alter digest',()=>{const x=fixture(),y=Object.fromEntries(Object.entries(x).reverse());assert.equal(checkUiRegression(x).data.provenance.inputSha256,checkUiRegression(y).data.provenance.inputSha256);});
test('input array ordering preserves precise evidence locators',()=>{const r=checkUiRegression(fixture());assert.ok(r.data.checks.every(c=>c.evidence.every(p=>p.startsWith('/cases/0'))));});
test('case cap rejects instead of silently clipping',()=>{const x=fixture();x.cases=Array.from({length:33},(_,i)=>({...structuredClone(x.cases[0]),id:'case-'+i}));assert.equal(checkUiRegression(x).status,'error');});
test('bounded output fallback is valid unknown JSON',()=>{const r=JSON.parse(encodeResult({status:'pass',data:'x'.repeat(LIMITS.outputBytes)}));assert.equal(r.status,'unknown');assert.equal(exitCode(r),3);assert.ok(resultSchema(r));});
test('capabilities expose current profile and planned business trace boundary',()=>{const r=capabilities();assert.equal(r.data.generalBusinessTraceImplemented,false);assert.ok(resultSchema(r),JSON.stringify(resultSchema.errors));});
test('repeat same snapshot gives byte-identical output',()=>assert.equal(encodeResult(checkUiRegression(fixture())),encodeResult(checkUiRegression(fixture()))));
test('duplicate JSON keys rejected including escaped equivalent keys',()=>{assert.throws(()=>parseJson('{"a":1,"a":2}'));assert.throws(()=>parseJson('{"a":1,"\\u0061":2}'));});
test('nested JSON depth rejected before parsing',()=>assert.throws(()=>parseJson('['.repeat(34)+'0'+']'.repeat(34))));
test('JSON trailing content and malformed literals rejected',()=>{for(const x of ['{}{}','[01]','{"a":NaN}','{"a":1,}','[1,]']) assert.throws(()=>parseJson(x));});
test('valid escaped JSON string parses',()=>assert.deepEqual(parseJson('{"a":"a\\\"b","b":[true,false,null,-1.2e3]}'),{a:'a"b',b:[true,false,null,-1200]}));
test('Unicode path inputs work without echoing path contents',()=>{const dir=mkdtempSync(join(tmpdir(),'ui-'));try {const file=join(dir,'测试 evidence.json');writeFileSync(file,JSON.stringify(fixture()));assert.equal(checkUiRegression(readJson(file)).status,'pass');const r=runCli(['ui-regression-check','--input',file,'--json']);assert.equal(r.code,0);assert.ok(!r.stdout.includes(file));}finally{rmSync(dir,{recursive:true,force:true});}});
test('bad file errors redact contents and paths',()=>{const r=runCli(['ui-regression-check','--input','/private/customer-secret.json','--json']);assert.equal(r.code,2);assert.ok(!r.stdout.includes('customer-secret'));});
test('credential files denied before reading and invalid UTF8 rejected',()=>{const dir=mkdtempSync(join(tmpdir(),'ui-'));try{const secret=join(dir,'.env');writeFileSync(secret,JSON.stringify(fixture()));assert.throws(()=>readJson(secret));const bad=join(dir,'bad.json');writeFileSync(bad,Buffer.from([0xff]));assert.throws(()=>readJson(bad));}finally{rmSync(dir,{recursive:true,force:true});}});
test('regular files and input byte cap required',()=>{const dir=mkdtempSync(join(tmpdir(),'ui-'));try {assert.throws(()=>readJson(dir));const big=join(dir,'big.json');writeFileSync(big,'x'.repeat(LIMITS.inputBytes+1));assert.throws(()=>readJson(big));}finally{rmSync(dir,{recursive:true,force:true});}});
test('credential symlink target denied', {skip:process.platform==='win32'},()=>{const dir=mkdtempSync(join(tmpdir(),'ui-'));try {const secret=join(dir,'auth.json'),link=join(dir,'safe.json');writeFileSync(secret,JSON.stringify(fixture()));symlinkSync(secret,link);assert.throws(()=>readJson(link));}finally{rmSync(dir,{recursive:true,force:true});}});
test('CLI rejects unknown/duplicate options and planned operations',()=>{for(const args of [['summarize','--json'],['ui-regression-check','--input','x','--json','--json'],['capabilities','--input','x'],['capabilities','--write']])assert.equal(runCli(args).code,2);});
test('CLI capabilities and help documented',()=>{assert.equal(JSON.parse(runCli(['capabilities','--json']).stdout).data.offline,true);assert.match(runCli(['--help']).stdout,/Exit 0 pass/);});
test('all status exit codes documented',()=>assert.deepEqual(['pass','fail','error','unknown'].map(status=>exitCode({status})),[0,1,2,3]));
test('circular API input rejected without internal exception',()=>{const x=fixture();x.loop=x;assert.equal(checkUiRegression(x).status,'error');});
