import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { createHash } from 'node:crypto';
import { collectEvidence, publicAddress } from '../src/collector.js';
import { verifyDeployment } from '../src/index.js';
const hash=x=>createHash('sha256').update(x).digest('hex');
async function fixture(t, handler) {
 const server=http.createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));
 return {schemaVersion:'1.0',expected:{commit:'a'.repeat(40),buildId:'build-1',origin:'http://127.0.0.1:'+server.address().port,assets:[{path:'/asset.js',sha256:hash('hello')}]},policy:{asOf:new Date(Date.now()+1000).toISOString(),maxEvidenceAgeSeconds:60,requiredChecks:['build']},collection:{allowLocalhost:true}};
}
test('observes actual body and dedicated version headers',async t=>{const request=await fixture(t,(_req,res)=>{res.setHeader('x-deploy-commit','a'.repeat(40));res.setHeader('x-deploy-build-id','build-1');res.end('hello');});const result=await collectEvidence(request);assert.equal(result.bundle.http[0].sha256,hash('hello'));assert.equal(result.bundle.http[0].commit,'a'.repeat(40));assert.equal(result.provenance.requests,1);assert.equal(verifyDeployment(result.bundle,{allowLocalhost:true}).status,'unknown');});
test('missing versions remain missing, secrets never echoed',async t=>{const request=await fixture(t,(_req,res)=>{res.setHeader('set-cookie','secret=abc');res.setHeader('x-deploy-build-id','ghp_secret');res.end('hello');});const result=await collectEvidence(request);assert.equal(result.bundle.http[0].commit,undefined);assert.equal(result.bundle.http[0].buildId,undefined);assert.ok(!JSON.stringify(result).includes('secret'));assert.equal(result.diagnostics[0].code,'VERSION_HEADERS_MISSING');});
test('localhost requires explicit opt-in',async t=>{const request=await fixture(t,(_req,res)=>res.end('hello'));delete request.collection.allowLocalhost;await assert.rejects(collectEvidence(request));});
test('rejects unknown configuration and credential URLs',async t=>{const request=await fixture(t,(_req,res)=>res.end('hello'));request.collection.headers={authorization:'secret'};await assert.rejects(collectEvidence(request));delete request.collection.headers;request.expected.origin=request.expected.origin.replace('://','://user:password@');await assert.rejects(collectEvidence(request));});
test('redirects remain in origin and actual asset scope is independently verified',async t=>{const request=await fixture(t,(req,res)=>{if(req.url==='/asset.js'){res.writeHead(302,{location:'/other.js'});res.end();}else res.end('hello');});const result=await collectEvidence(request);assert.equal(result.provenance.requests,2);assert.equal(result.bundle.http[0].redirects.length,1);assert.equal(verifyDeployment(result.bundle,{allowLocalhost:true}).status,'fail');});
test('cross-origin redirect is refused without request',async t=>{const request=await fixture(t,(_req,res)=>{res.writeHead(302,{location:'https://example.com/asset.js'});res.end();});const result=await collectEvidence(request);assert.equal(result.provenance.requests,1);assert.equal(result.bundle.http.length,0);});
test('body budget truncates collection without exposing payload',async t=>{const request=await fixture(t,(_req,res)=>res.end('hello'));request.collection.maxBodyBytes=2;const result=await collectEvidence(request);assert.equal(result.bundle.http.length,0);assert.equal(result.diagnostics[0].code,'BODY_LIMIT');});
test('timeout bounded and no observation fabricated',async t=>{const request=await fixture(t,(_req,res)=>{setTimeout(()=>res.end('hello'),60);});request.collection.timeoutMs=10;const result=await collectEvidence(request);assert.equal(result.bundle.http.length,0);assert.equal(result.diagnostics[0].code,'TIMEOUT');});
test('request budget stops redirects',async t=>{const request=await fixture(t,(_req,res)=>{res.writeHead(302,{location:'/other.js'});res.end();});request.collection.maxRequests=1;const result=await collectEvidence(request);assert.equal(result.diagnostics[0].code,'REQUEST_LIMIT');});
test('304 does not hash absent cached representation',async t=>{const request=await fixture(t,(_req,res)=>{res.writeHead(304);res.end();});const result=await collectEvidence(request);assert.equal(result.bundle.http[0].sha256,undefined);assert.ok(result.diagnostics.some(x=>x.code==='BODY_HASH_UNAVAILABLE'));});
test('DNS address policy conservative deny ranges',()=>{for(const a of ['127.0.0.1','10.0.0.1','169.254.1.1','172.16.0.1','192.168.0.1','100.64.0.1','198.18.0.1','192.0.2.1','203.0.113.1','::1','fc00::1','fe80::1','::ffff:8.8.8.8','2001:db8::1'])assert.equal(publicAddress(a),false,a);for(const a of ['8.8.8.8','1.1.1.1','2606:4700:4700::1111'])assert.equal(publicAddress(a),true,a);});
test('supplied CI/browser retained without fabricating values',async t=>{const request=await fixture(t,(_req,res)=>res.end('hello'));request.ci=[{id:'ci1',observedAt:request.policy.asOf,check:'build',commit:'a'.repeat(40),buildId:'build-1',conclusion:'pass'}];const result=await collectEvidence(request);assert.deepEqual(result.bundle.ci,request.ci);assert.equal(result.bundle.browser,undefined);assert.equal(result.provenance.browser,'supplied-sanitized-evidence-only');});
test('response encoding leaves representation hash unknown',async t=>{const request=await fixture(t,(_req,res)=>{res.setHeader('content-encoding','gzip');res.end('not actually gzip');});const result=await collectEvidence(request);assert.equal(result.bundle.http[0].sha256,undefined);});
test('redirect limit independent of request limit',async t=>{const request=await fixture(t,(_req,res)=>{res.writeHead(302,{location:'/asset.js'});res.end();});const result=await collectEvidence(request);assert.equal(result.provenance.requests,6);assert.equal(result.diagnostics[0].code,'REDIRECT_LIMIT');});
test('invalid budgets fail before collection',async t=>{const request=await fixture(t,(_req,res)=>res.end('hello'));for(const [key,value] of [['timeoutMs',30001],['maxRequests',0],['maxBodyBytes',4194305]]){request.collection[key]=value;await assert.rejects(collectEvidence(request));delete request.collection[key];}});
test('collection cutoff follows observations and total duration stops later requests',async t=>{const request=await fixture(t,(_req,res)=>setTimeout(()=>res.end('hello'),50));request.collection.maxDurationMs=10;request.expected.assets.push({path:'/second.js',sha256:hash('hello')});const result=await collectEvidence(request);assert.ok(result.provenance.requests<=2);assert.ok(result.diagnostics.every(x=>['TIMEOUT','DURATION_LIMIT'].includes(x.code)));assert.equal(result.bundle.http.length,0);assert.equal(result.bundle.policy.asOf,result.provenance.cutoff);});
